# Generated by Django 4.1.7 on 2023-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quize',
            name='question',
        ),
        migrations.AddField(
            model_name='quize',
            name='question',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
