# Generated by Django 4.1.7 on 2023-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_answers_iscorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='val',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
