# Generated by Django 4.1.7 on 2023-04-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_answers_quizeid_alter_quize_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='quizeId',
        ),
    ]
