# Generated by Django 4.1.7 on 2023-04-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_remove_answers_quizeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizes.quize'),
        ),
    ]
