# Generated by Django 4.1.7 on 2023-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_answers_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
