# Generated by Django 4.1.7 on 2023-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_alter_quize_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='question',
            field=models.UUIDField(),
        ),
    ]
