# Generated by Django 4.1.7 on 2023-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_remove_answers_question_alter_answers_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ManyToManyField(to='quizes.quize'),
        ),
    ]
